"""
LangGraph agent state definition.
"""

from __future__ import annotations

from typing import Any
from typing_extensions import TypedDict


class AgentState(TypedDict, total=False):
    """
    Shared state flowing through all graph nodes.

    Fields
    ------
    user_question:
        The raw (pre-sanitised) question from the merchant.
    merchant_id:
        The authenticated merchant identifier (e.g. "mch_001").
    intent:
        Classified intent: "transaction" | "api_docs" | "ambiguous".
    confidence:
        Classifier confidence score between 0.0 and 1.0.
    sql_params:
        Structured parameters extracted by the LLM for DB queries.
        Keys: date_filter, status, limit, error_code.
    db_results:
        List of transaction row dicts returned by the DB tool.
    retrieved_docs:
        List of doc chunk dicts returned by the docs tool.
    sql_query:
        The final parameterized SQL string that was executed (for display).
    response:
        The final natural-language answer generated by the LLM.
    error:
        Non-empty string if any node encountered an unrecoverable error.
    """

    user_question: str
    merchant_id: str
    intent: str
    confidence: float
    sql_params: dict[str, Any]
    db_results: list[dict[str, Any]]
    retrieved_docs: list[dict[str, Any]]
    sql_query: str
    response: str
    error: str
